//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.tasklist.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_task
    {
        public System.Guid ID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Finished { get; set; }
        public bool IsCompleted { get; set; }
    }
}
